service: dragon-upload
frameworkVersion: 3.38.0

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  region: us-west-1
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, "dev"}
  environment:
    ${file(./config/${opt:stage, 'dev'}.yaml)}
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

functions:
  upload: ${file('./functions/Upload.yaml')}
  zipper: ${file('./functions/Zipper.yaml')}
  listZipped: ${file('./functions/ListZipped.yaml')}
  websocketConnect: ${file('./functions/WebSocketConnect.yaml')}
  websocketDisconnect: ${file('./functions/WebSocketDisconnect.yaml')}
  websocketOnMessage: ${file('./functions/WebSocketOnMessage.yaml')}

package:
  individually: true
  patterns:
    - '!functions/**'
    - '!config/**'
    - '!resources/**'
    - '!mocks/**'
    - '!src/**'

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline

resources:
  Resources:
    UploadRole: ${file(./resources/UploadRole.yaml)}
    DragonlandBucket: ${file(./resources/DragonlandBucket.yaml)}
    ZipFileQueue: ${file(./resources/ZipfileSQS.yaml)}
    FilesTable: ${file(./resources/FilesDynamoDb.yaml)}
    ConnectionsWebsocketTable: ${file(./resources/ConnectionsWsDynamoDb.yaml)}
